---
version: "3"

services:
  motion:
    image: ipcamstream-xyz-client
    container_name: ipcamstream-xyz-client
    networks: 
      - proxy
    volumes:
      - ./config:/app/config
      - ./bin:/app/bin
    environment:
      TZ: 'America/Sao_Paulo'
    restart: unless-stopped
networks:
  proxy:
    external: true
